name: Validate Synthetic Data Script

on: [push,pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest
        pip install pandas
        pip install numpy
        pip install faker

    - name: Run tests
      run: |
        python generate_data.py
        python validate_data.py
        
    - name: Generate data files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: synthetic_data
        path: /
    - name: checkout output-files
      run: |
       ls
      
